backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: Member,
              name: member,
              widget: list,
              fields:
                [
                  { label: Image, name: image, widget: image },
                  { label: Name, name: name, widget: text },
                  { label: Body, name: body, widget: markdown },
                ],
            }
      - file: "src/pages/clients/index.md"
        label: "Clients"
        name: "clients"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "clients-page",
            }
          - {
              label: Quotes,
              name: quotes,
              widget: list,
              fields:
                [
                  { label: Quote, name: quote, widget: text },
                  { label: Author, name: author, widget: text },
                ],
            }
      - file: "src/pages/donate/index.md"
        label: "Donate"
        name: "donate"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "donate-page",
            }
          - { label: Text, name: text, widget: text }
      - file: "src/pages/contact/index.md"
        label: "Contact"
        name: "contact"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "contact-page",
            }
          - { label: Phone, name: phone, widget: text }
          - { label: Email, name: email, widget: text }
      - file: "src/pages/complaints/index.md"
        label: "Complaints"
        name: "complaints"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "complaints-page",
            }
          - { label: Body, name: body, widget: markdown }
          - { label: Image, name: image, widget: image }
      - file: "src/pages/blog/index.md"
        label: "Blog Page"
        name: "blogpage"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "blog-page",
            }
          - { label: Body, name: body, widget: markdown }
      - file: "src/pages/expertise/index.md"
        label: "Expertise"
        name: "expertise"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "expertise-page",
            }
          - {
              label: Areas of Expertise,
              name: areas,
              widget: list,
              fields:
                [
                  { label: Name, name: name, widget: text },
                  { label: Body, name: body, widget: markdown },
                ],
            }
